title: KK
logo: /profile.jpg
theme: jekyll-theme-minimal
description: [Undergraduate of Seoul National University

Mathematical Sciences and Statistics (Double Major)

Part-time Instructor at P&K Math Academy

dizict0120 (at) snu.ac.kr]

