title: KK
logo: /profile.jpg
description: [Undergraduate of Seoul National University
Mathematical Sciences, Statistics (Double Major)
Part-time Instructor at P&K Math Academy
dizict0120 (at) snu.ac.kr]

theme: jekyll-theme-minimal

